In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [19]:
orders_products_merged = pd.read_csv(r"C:\Users\danie\_orders_products\orders_products_merged.csv")

In [20]:
path= r"C:\Users\danie\_orders_products\orders_products_merged.csv"

In [23]:
orders_products_merged.shape

(32404859, 22)

In [24]:
orders_products_merged.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,0,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
2,2,2,11,473747,1,prior,3,3,12,21.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,1,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow
4,4,4,21,431534,1,prior,5,4,15,28.0,...,1,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow

In [25]:
# Create a subset
df = orders_products_merged [:1000000]

In [26]:
df.shape

(1000000, 22)

In [28]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,reordered,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,0,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
2,2,2,11,473747,1,prior,3,3,12,21.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,1,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow
4,4,4,21,431534,1,prior,5,4,15,28.0,...,1,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow
5,5,5,29,3367565,1,prior,6,2,7,19.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
6,6,6,33,550135,1,prior,7,1,9,20.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
7,7,7,39,3108588,1,prior,8,1,14,14.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
8,8,8,47,2295261,1,prior,9,1,16,0.0,...,1,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow
9,9,9,50,2550362,1,prior,10,4,8,30.0,...,1,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow

In [29]:
df.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [30]:
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [31]:
# Mutiple Aggregations
df.groupby('department_id').agg({'order_number':['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [32]:
orders_products_merged['max_order'] = orders_products_merged.groupby(['user_id'])['order_number'].transform(np.max)

In [33]:
orders_products_merged.head(15)

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days,max_order
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
2,2,2,11,473747,1,prior,3,3,12,21.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
4,4,4,21,431534,1,prior,5,4,15,28.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
5,5,5,29,3367565,1,prior,6,2,7,19.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
6,6,6,33,550135,1,prior,7,1,9,20.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
7,7,7,39,3108588,1,prior,8,1,14,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
8,8,8,47,2295261,1,prior,9,1,16,0.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
9,9,9,50,2550362,1,prior,10,4,8,30.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
10,10,10,1391,2968173,15,prior,15,1,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
11,11,11,1402,1870022,15,prior,17,2,16,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
12,12,12,1403,1911383,15,prior,18,2,11,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
13,13,13,1412,2715276,15,prior,21,1,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
14,14,14,1414,487368,15,prior,22,1,10,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22

In [34]:
orders_products_merged.head(100)

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days,max_order
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
2,2,2,11,473747,1,prior,3,3,12,21.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
4,4,4,21,431534,1,prior,5,4,15,28.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,55291,3226575,360,prior,1,5,12,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
96,96,96,57452,1469869,377,prior,3,5,17,3.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
97,97,97,58490,1927023,387,prior,2,4,10,22.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,8
98,98,98,63584,858092,420,prior,4,1,19,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
99,99,99,63591,119314,420,prior,5,3,19,16.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22

In [36]:
pd.options.display.max_rows = None

In [37]:
orders_products_merged.head(100)

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,_merge,Unnamed: 0_y,product_name,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days,max_order
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
2,2,2,11,473747,1,prior,3,3,12,21.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
4,4,4,21,431534,1,prior,5,4,15,28.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
5,5,5,29,3367565,1,prior,6,2,7,19.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
6,6,6,33,550135,1,prior,7,1,9,20.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
7,7,7,39,3108588,1,prior,8,1,14,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
8,8,8,47,2295261,1,prior,9,1,16,0.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10
9,9,9,50,2550362,1,prior,10,4,8,30.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,10
10,10,10,1391,2968173,15,prior,15,1,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
11,11,11,1402,1870022,15,prior,17,2,16,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
12,12,12,1403,1911383,15,prior,18,2,11,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
13,13,13,1412,2715276,15,prior,21,1,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
14,14,14,1414,487368,15,prior,22,1,10,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
15,15,15,1853,2293453,19,prior,2,5,14,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,9
16,16,16,1928,1973799,19,prior,5,6,12,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,9
17,17,17,1955,532817,19,prior,7,4,17,6.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,9
18,18,18,2104,1573906,21,prior,10,3,10,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,33
19,19,19,3772,1593000,31,prior,10,3,8,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,20
20,20,20,3909,2231262,31,prior,17,3,11,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,20
21,21,21,5384,2580647,43,prior,6,4,16,4.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,11
22,22,22,5421,2187180,43,prior,9,4,12,3.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,11
23,23,23,6352,2497897,52,prior,1,1,9,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
24,24,24,6359,1318871,52,prior,2,1,10,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
25,25,25,6363,1261384,52,prior,3,1,10,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
26,26,26,6378,580568,52,prior,5,2,10,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
27,27,27,6388,2428073,52,prior,7,2,7,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
28,28,28,6401,342306,52,prior,9,1,11,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
29,29,29,6405,1520353,52,prior,10,2,10,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
30,30,30,6412,2542086,52,prior,11,2,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
31,31,31,6420,944694,52,prior,12,1,16,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
32,32,32,6433,1268191,52,prior,15,2,11,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
33,33,33,6444,1122089,52,prior,17,2,10,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
34,34,34,6454,1498922,52,prior,18,2,10,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
35,35,35,6465,180919,52,prior,19,3,8,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
36,36,36,6480,2695875,52,prior,21,5,10,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,27
37,37,37,8693,3205960,67,prior,1,3,11,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
38,38,38,8698,970922,67,prior,2,1,15,5.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
39,39,39,8704,596585,67,prior,3,1,13,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
40,40,40,8706,2037087,67,prior,4,2,9,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
41,41,41,8710,2474111,67,prior,5,3,14,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
42,42,42,8712,1568481,67,prior,6,3,12,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
43,43,43,8718,2048527,67,prior,8,2,11,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
44,44,44,8721,2389031,67,prior,9,2,14,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
45,45,45,8724,2378562,67,prior,10,1,10,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
46,46,46,8726,1515698,67,prior,11,1,11,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
47,47,47,8730,1928050,67,prior,12,2,12,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
48,48,48,8734,1949274,67,prior,13,1,10,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
49,49,49,8738,551869,67,prior,14,1,9,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
50,50,50,8744,768572,67,prior,16,4,10,9.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,24
51,51,51,8748,150528,67,prior,18,5,16,4.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
52,52,52,8754,29758,67,prior,19,0,14,9.0,...,both,195,Soda,77,7,9.0,Busiest day,Busiest days,slowest days,24
53,53,53,8758,1558976,67,prior,21,1,9,5.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
54,54,54,8765,863974,67,prior,22,1,11,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
55,55,55,8766,2308399,67,prior,23,1,14,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,24
56,56,56,10367,2759128,81,prior,3,1,9,14.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,7
57,57,57,10375,1812985,81,prior,5,2,20,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,7
58,58,58,10394,1889835,82,prior,1,3,15,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
59,59,59,10404,499460,82,prior,3,5,10,5.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
60,60,60,10405,2728456,82,prior,4,0,11,16.0,...,both,195,Soda,77,7,9.0,Busiest day,Busiest days,slowest days,19
61,61,61,10428,2653743,82,prior,6,4,9,13.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,19
62,62,62,10438,1358880,82,prior,9,1,10,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
63,63,63,10447,343588,82,prior,10,2,11,1.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
64,64,64,10490,3034663,82,prior,15,2,11,12.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
65,65,65,10513,147262,82,prior,18,1,13,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
66,66,66,10514,3144004,82,prior,19,2,15,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,19
67,67,67,12688,2126069,98,prior,3,0,9,25.0,...,both,195,Soda,77,7,9.0,Busiest day,Busiest days,slowest days,14
68,68,68,12702,2210120,98,prior,7,5,14,5.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,14
69,69,69,12710,681011,98,prior,9,3,9,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,14
70,70,70,12715,2846344,98,prior,11,4,13,15.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,14
71,71,71,12720,747431,98,prior,12,6,13,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,14
72,72,72,12722,2383054,98,prior,13,4,11,30.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,14
73,73,73,12724,1993729,98,prior,14,5,8,8.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,14
74,74,74,13559,1403849,109,prior,3,3,17,9.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,6
75,75,75,14654,520620,120,prior,1,3,11,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
76,76,76,14658,3273029,120,prior,3,2,8,19.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
77,77,77,24937,1861943,185,prior,2,1,12,25.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,6
78,78,78,25701,2040988,195,prior,1,1,14,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
79,79,79,25717,1680569,195,prior,8,1,9,4.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
80,80,80,25744,276171,195,prior,19,5,11,3.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
81,81,81,25753,2744976,195,prior,22,5,10,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
82,82,82,25759,2781919,195,prior,25,1,14,4.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
83,83,83,25779,1738718,195,prior,31,2,8,4.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
84,84,84,25790,3058369,195,prior,34,3,10,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
85,85,85,25802,1485596,195,prior,37,2,15,0.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
86,86,86,25816,417035,195,prior,40,3,16,2.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
87,87,87,25845,1615297,195,prior,47,5,10,2.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
88,88,88,25863,1765587,195,prior,52,3,12,2.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,58
89,89,89,25880,745908,195,prior,57,4,11,3.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,58
90,90,90,31542,2505656,222,prior,17,2,12,1.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,70
91,91,91,31685,3268370,222,prior,38,5,15,1.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,70
92,92,92,43570,2016711,290,prior,9,5,19,6.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,51
93,93,93,44182,2706088,290,prior,28,6,10,7.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,51
94,94,94,51879,1952286,331,prior,6,5,16,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,8
95,95,95,55291,3226575,360,prior,1,5,12,NaN,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
96,96,96,57452,1469869,377,prior,3,5,17,3.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,3
97,97,97,58490,1927023,387,prior,2,4,10,22.0,...,both,195,Soda,77,7,9.0,Least busy,Least busy,Least slow,8
98,98,98,63584,858092,420,prior,4,1,19,30.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22
99,99,99,63591,119314,420,prior,5,3,19,16.0,...,both,195,Soda,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,22

In [41]:
# Deriving Columns with Loc()
orders_products_merged.loc[orders_products_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [42]:
orders_products_merged.loc[(orders_products_merged['max_order'] <= 40) & (orders_products_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [43]:
orders_products_merged.loc[orders_products_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [44]:
orders_products_merged['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [47]:
orders_products_merged[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

Question 2

In [52]:
# Comparing subset to Dataframe
orders_products_merged.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

In [53]:
df.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

With the exception of department ID 17, The mean is higher in the DF vs the subset

In [54]:
# Deriving Columns with Loc()
orders_products_merged.loc[orders_products_merged['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [55]:
orders_products_merged.loc[(orders_products_merged['max_order'] <= 40) & (orders_products_merged['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [56]:
orders_products_merged.loc[orders_products_merged['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [57]:
orders_products_merged['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [58]:
# Product price for each (Loyal Customer, Regular Customer, and New Customer)
orders_products_merged['average_price'] = orders_products_merged.groupby(['user_id'])['prices'].transform(np.mean)

In [63]:
orders_products_merged.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days,max_order,loyalty_flag,average_price,spending_flag
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
2,2,2,11,473747,1,prior,3,3,12,21.0,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,77,7,9.0,Least busy,Least busy,Least slow,10,New customer,6.367797,Low spender
4,4,4,21,431534,1,prior,5,4,15,28.0,...,77,7,9.0,Least busy,Least busy,Least slow,10,New customer,6.367797,Low spender

Question 6

In [60]:
# creating "Spending_flag" for average price < 10 as low spender
orders_products_merged.loc[orders_products_merged['average_price'] < 10, 'spending_flag'] = 'Low spender'

In [61]:
# creating "Spending_flag" for average price >= 10 as High spender
orders_products_merged.loc[orders_products_merged['average_price'] >= 10, 'spending_flag'] = 'High spender'

In [62]:
orders_products_merged['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

In [64]:
orders_products_merged.head()

,Unnamed: 0.1,Unnamed: 0,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,...,aisle_id,department_id,prices,busiest_day,busiest_days,slowest_days,max_order,loyalty_flag,average_price,spending_flag
0,0,0,0,2539329,1,prior,1,2,8,NaN,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
1,1,1,5,2398795,1,prior,2,3,7,15.0,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
2,2,2,11,473747,1,prior,3,3,12,21.0,...,77,7,9.0,Regularly busy,Regularly busy,Regularly slow,10,New customer,6.367797,Low spender
3,3,3,16,2254736,1,prior,4,4,7,29.0,...,77,7,9.0,Least busy,Least busy,Least slow,10,New customer,6.367797,Low spender
4,4,4,21,431534,1,prior,5,4,15,28.0,...,77,7,9.0,Least busy,Least busy,Least slow,10,New customer,6.367797,Low spender

Question 7
   If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
  If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [72]:
# Create order Frequency
orders_products_merged['median_orders'] = orders_products_merged.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [73]:
orders_products_merged.loc[orders_products_merged['median_orders'] >20, 'order_frequency_flag'] = 'Non-frequent_customer'

In [75]:
orders_products_merged.loc[orders_products_merged['median_orders'] >10 & (orders_products_merged['median_orders']<=20), 'order_frequency_flag'] = 'Regular_customer'

In [76]:
orders_products_merged.loc[orders_products_merged['median_orders'] <=10, 'order_frequency_flag'] = 'frequent_customer'

In [77]:
orders_products_merged['order_frequency_flag'].value_counts(dropna = False)

order_frequency_flag
frequent_customer    21559853
Regular_customer     10845001
NaN                         5
Name: count, dtype: int64

In [78]:
orders_products_merged.to_csv(r"C:\Users\danie\_orders_products\orders_products_merged.csv")